# Global Forest Watch API
# Copyright (C) 2013 World Resource Institute
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

application: gfw-apis
module: testingadrianapi
version: v1-wip
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- mail
# - warmup

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "latest"

## GAE python console:
# remote_api_shell.py -s dev.gfw-apis.appspot.com
builtins:
- remote_api: on

handlers:

## Earth Engine dep:
- url: /oauth2callback
  script: oauth2client.appengine.application

- url: /_ah/mail/sub.*
  script: gfw.pubsub.handlers
  login: admin

- url: /_info
  script: gfw.info.handlers

# Download handler:
- url: /analysis/(imazon|forma|modis|prodes).(shp|geojson|kml|svg|csv)
  script: download.handlers

# Analysis handler:
- url: /analysis/(imazon|forma|modis|umd|prodes|biomassloss|guyra|glad)
  script: analysis.handlers

# Monitor
- url: /monitor.*
  script: monitor.handlers

- url: /gee.*
  script: gfw.gee_tiles.api

- url: /admin.*
  script: admin.handlers
  login: admin

# Forest change handlers
- url: /forest-change
  script: gfw.forestchange.api.handlers

# Country handlers
- url: /countries.*
  script: gfw.countries.api.handlers

- url: /forest-change/(forma-alerts|umd-loss-gain|imazon-alerts|quicc-alerts|nasa-active-fires|terrai-alerts|glad-alerts|prodes-loss|biomass-loss|guyra-loss|loss-by-type).*
  script: gfw.forestchange.api.handlers

# Stories
- url: /stories.*
  script: gfw.stories.handlers

# User Info
- url: /user.*
  script: gfw.user.api.handlers

- url: /metadata.*
  script: gfw.metadata.handlers

## Version 2

# Subscriptions
- url: /v2/subscriptions.*
  script: gfw.v2.subscriptions.api.handlers

# PubSub
- url: /.*
  script: gfw.pubsub.api.handlers
